/**
 * Angular Material Theme Generator
 * Generates Angular Material SCSS theme
 *
 * @module @spexop/theme/generators
 */

import type { SpexopThemeConfig } from "../types/SpexopThemeConfig.js";

/**
 * Generate Angular Material theme
 *
 * @param config - Spexop theme configuration
 * @returns Angular Material SCSS string
 */
export function generateAngular(config: SpexopThemeConfig): string {
  const { colors, spacing, typography } = config;

  return `/**
 * ${config.meta.name} - Angular Material Theme
 * Generated by @spexop/theme
 * Version: ${config.meta.version}
 */

@use '@angular/material' as mat;

// Define the theme palette
$theme-primary: (
  50: ${colors.surfaceHover},
  100: ${colors.surfaceSecondary},
  200: ${colors.border},
  300: ${colors.borderStrong},
  400: ${colors.primaryHover || colors.primary},
  500: ${colors.primary},
  600: ${colors.primaryActive || colors.primary},
  700: ${colors.text},
  800: ${colors.text},
  900: ${colors.text},
  contrast: (
    50: ${colors.text},
    100: ${colors.text},
    200: ${colors.text},
    300: ${colors.text},
    400: ${colors.surface},
    500: ${colors.surface},
    600: ${colors.surface},
    700: ${colors.surface},
    800: ${colors.surface},
    900: ${colors.surface},
  ),
);

$theme-accent: (
  50: ${colors.surfaceHover},
  100: ${colors.surfaceSecondary},
  200: ${colors.border},
  300: ${colors.borderStrong},
  400: ${colors.secondary || colors.primary},
  500: ${colors.secondary || colors.primary},
  600: ${colors.secondary || colors.primary},
  700: ${colors.text},
  800: ${colors.text},
  900: ${colors.text},
  contrast: (
    50: ${colors.text},
    100: ${colors.text},
    200: ${colors.text},
    300: ${colors.text},
    400: ${colors.surface},
    500: ${colors.surface},
    600: ${colors.surface},
    700: ${colors.surface},
    800: ${colors.surface},
    900: ${colors.surface},
  ),
);

// Create the theme
$theme: mat.define-light-theme((
  color: (
    primary: mat.define-palette($theme-primary),
    accent: mat.define-palette($theme-accent),
  ),
  typography: mat.define-typography-config(
    $font-family: ${typography.fontFamily},
    $headline-1: mat.define-typography-level(${Math.round(typography.baseSize * typography.scale ** 6)}px, ${typography.lineHeights.tight}, ${typography.weights.bold}),
    $headline-2: mat.define-typography-level(${Math.round(typography.baseSize * typography.scale ** 5)}px, ${typography.lineHeights.tight}, ${typography.weights.bold}),
    $headline-3: mat.define-typography-level(${Math.round(typography.baseSize * typography.scale ** 4)}px, ${typography.lineHeights.tight}, ${typography.weights.semibold}),
    $headline-4: mat.define-typography-level(${Math.round(typography.baseSize * typography.scale ** 3)}px, ${typography.lineHeights.normal}, ${typography.weights.semibold}),
    $body-1: mat.define-typography-level(${typography.baseSize}px, ${typography.lineHeights.normal}, ${typography.weights.regular}),
  ),
));

// Include theme
@include mat.all-component-themes($theme);

// Custom CSS variables for additional theme values
:root {
  --theme-spacing-base: ${spacing.baseUnit}px;
}
`;
}
