/**
 * Docusaurus Theme Generator
 * Generates Docusaurus theme configuration
 *
 * @module @spexop/theme/generators
 */

import type { SpexopThemeConfig } from "../types/SpexopThemeConfig.js";

/**
 * Generate Docusaurus theme
 *
 * @param config - Spexop theme configuration
 * @returns Docusaurus theme JavaScript string
 */
export function generateDocusaurus(config: SpexopThemeConfig): string {
  const { colors, typography } = config;

  return `/**
 * ${config.meta.name} - Docusaurus Theme
 * Generated by @spexop/theme
 * Version: ${config.meta.version}
 */

// docusaurus.config.js theme colors
export const themeConfig = {
  colorMode: {
    defaultMode: 'light',
    disableSwitch: false,
    respectPrefersColorScheme: true,
  },
  docs: {
    sidebar: {
      hideable: true,
    },
  },
  navbar: {
    style: 'primary',
  },
  prism: {
    theme: require('prism-react-renderer/themes/github'),
    darkTheme: require('prism-react-renderer/themes/dracula'),
  },
};

// Custom CSS for Docusaurus (add to src/css/custom.css)
export const customCSS = \`
/**
 * Custom Docusaurus Theme
 * Based on ${config.meta.name}
 */

:root {
  /* Primary colors */
  --ifm-color-primary: ${colors.primary};
  --ifm-color-primary-dark: ${colors.primaryActive || colors.primary};
  --ifm-color-primary-darker: ${colors.primaryActive || colors.primary};
  --ifm-color-primary-darkest: ${colors.primaryActive || colors.primary};
  --ifm-color-primary-light: ${colors.primaryHover || colors.primary};
  --ifm-color-primary-lighter: ${colors.primaryHover || colors.primary};
  --ifm-color-primary-lightest: ${colors.primaryHover || colors.primary};

  /* Background */
  --ifm-background-color: ${colors.surface};
  --ifm-background-surface-color: ${colors.surfaceSecondary};

  /* Text */
  --ifm-font-color-base: ${colors.text};
  --ifm-font-color-secondary: ${colors.textSecondary};

  /* Typography */
  --ifm-font-family-base: ${typography.fontFamily};
  --ifm-font-size-base: ${typography.baseSize}px;
  ${typography.fontFamilyMono ? `--ifm-font-family-monospace: ${typography.fontFamilyMono};` : ""}

  /* Borders */
  --ifm-global-border-width: ${colors.border};
  --ifm-global-radius: ${config.borders.radiusRelaxed}px;

  /* Code blocks */
  --ifm-code-font-size: ${Math.round(typography.baseSize * 0.875)}px;
}

[data-theme='dark'] {
  --ifm-background-color: #0a0a0a;
  --ifm-background-surface-color: #171717;
  --ifm-font-color-base: #fafafa;
  --ifm-font-color-secondary: #a3a3a3;
}
\`;
`;
}
