/**
 * Less Variables Generator
 * Generates Less variables from theme config
 *
 * @module @spexop/theme/generators
 */

import type { SpexopThemeConfig } from "../types/SpexopThemeConfig.js";

/**
 * Generate Less variables
 *
 * @param config - Spexop theme configuration
 * @returns Less variables string
 */
export function generateLess(config: SpexopThemeConfig): string {
  const { colors, spacing, typography, borders, breakpoints } = config;

  // Generate spacing values
  const spacingValues = spacing.values || {
    0: 0,
    1: spacing.scale?.[1] || spacing.baseUnit,
    2: spacing.scale?.[2] || spacing.baseUnit * 2,
    3: spacing.scale?.[3] || spacing.baseUnit * 3,
    4: spacing.scale?.[4] || spacing.baseUnit * 4,
    5: spacing.scale?.[5] || spacing.baseUnit * 5,
    6: spacing.scale?.[6] || spacing.baseUnit * 6,
    7: spacing.scale?.[7] || spacing.baseUnit * 7,
    8: spacing.scale?.[8] || spacing.baseUnit * 8,
    9: spacing.scale?.[9] || spacing.baseUnit * 9,
    10: spacing.scale?.[10] || spacing.baseUnit * 10,
  };

  return `/**
 * ${config.meta.name} - Less Variables
 * Generated by @spexop/theme
 * Version: ${config.meta.version}
 */

// === Colors ===

// Primary
@theme-primary: ${colors.primary};
@theme-primary-hover: ${colors.primaryHover || colors.primary};
@theme-primary-active: ${colors.primaryActive || colors.primary};

// Secondary
${colors.secondary ? `@theme-secondary: ${colors.secondary};` : ""}
${colors.secondaryHover ? `@theme-secondary-hover: ${colors.secondaryHover};` : ""}
${colors.secondaryActive ? `@theme-secondary-active: ${colors.secondaryActive};` : ""}

// Surface
@theme-surface: ${colors.surface};
@theme-surface-secondary: ${colors.surfaceSecondary};
@theme-surface-hover: ${colors.surfaceHover};

// Text
@theme-text: ${colors.text};
@theme-text-secondary: ${colors.textSecondary};
@theme-text-muted: ${colors.textMuted};

// Border
@theme-border: ${colors.border};
@theme-border-strong: ${colors.borderStrong};
@theme-border-subtle: ${colors.borderSubtle};

// Semantic
${colors.success ? `@theme-success: ${colors.success};` : ""}
${colors.warning ? `@theme-warning: ${colors.warning};` : ""}
${colors.error ? `@theme-error: ${colors.error};` : ""}
${colors.info ? `@theme-info: ${colors.info};` : ""}

// === Spacing ===

${Object.entries(spacingValues)
  .map(([key, value]) => `@theme-spacing-${key}: ${value}px;`)
  .join("\n")}

// === Typography ===

// Font Families
@theme-font-family: ${typography.fontFamily};
@theme-font-family-heading: ${typography.fontFamilyHeading || typography.fontFamily};
${typography.fontFamilyMono ? `@theme-font-family-mono: ${typography.fontFamilyMono};` : ""}

// Font Sizes
@theme-font-size-xs: ${Math.round(typography.baseSize / (typography.scale * typography.scale))}px;
@theme-font-size-sm: ${Math.round(typography.baseSize / typography.scale)}px;
@theme-font-size-base: ${typography.baseSize}px;
@theme-font-size-lg: ${Math.round(typography.baseSize * typography.scale)}px;
@theme-font-size-xl: ${Math.round(typography.baseSize * typography.scale * typography.scale)}px;
@theme-font-size-2xl: ${Math.round(typography.baseSize * typography.scale ** 3)}px;

// Font Weights
@theme-font-weight-regular: ${typography.weights.regular};
@theme-font-weight-semibold: ${typography.weights.semibold};
@theme-font-weight-bold: ${typography.weights.bold};

// Line Heights
@theme-line-height-tight: ${typography.lineHeights.tight};
@theme-line-height-normal: ${typography.lineHeights.normal};
@theme-line-height-relaxed: ${typography.lineHeights.relaxed};

// === Borders ===

@theme-border-thin: ${borders.thin}px;
@theme-border-width: ${borders.default}px;
@theme-border-thick: ${borders.thick}px;

@theme-radius-subtle: ${borders.radiusSubtle}px;
@theme-radius-relaxed: ${borders.radiusRelaxed}px;
@theme-radius-pill: ${borders.radiusPill}px;

@theme-border-style: ${borders.defaultStyle};

// === Breakpoints ===

@theme-breakpoint-xs: ${breakpoints?.xs || 320}px;
@theme-breakpoint-sm: ${breakpoints?.sm || 640}px;
@theme-breakpoint-md: ${breakpoints?.md || 768}px;
@theme-breakpoint-lg: ${breakpoints?.lg || 1024}px;
@theme-breakpoint-xl: ${breakpoints?.xl || 1280}px;
@theme-breakpoint-2xl: ${breakpoints?.["2xl"] || 1536}px;
`;
}
