/**
 * PostCSS Plugin Generator
 * Generates PostCSS plugin for build-time token injection
 *
 * @module @spexop/theme/generators
 */

import type { SpexopThemeConfig } from "../types/SpexopThemeConfig.js";

/**
 * Generate PostCSS plugin
 *
 * @param config - Spexop theme configuration
 * @returns PostCSS plugin JavaScript string
 */
export function generatePostCSS(config: SpexopThemeConfig): string {
  const { colors, spacing, typography, borders } = config;

  const spacingValues = spacing.values || {
    0: 0,
    1: spacing.scale?.[1] || spacing.baseUnit,
    2: spacing.scale?.[2] || spacing.baseUnit * 2,
    3: spacing.scale?.[3] || spacing.baseUnit * 3,
    4: spacing.scale?.[4] || spacing.baseUnit * 4,
    5: spacing.scale?.[5] || spacing.baseUnit * 5,
    6: spacing.scale?.[6] || spacing.baseUnit * 6,
    7: spacing.scale?.[7] || spacing.baseUnit * 7,
    8: spacing.scale?.[8] || spacing.baseUnit * 8,
    9: spacing.scale?.[9] || spacing.baseUnit * 9,
    10: spacing.scale?.[10] || spacing.baseUnit * 10,
  };

  return `/**
 * ${config.meta.name} - PostCSS Plugin
 * Generated by @spexop/theme
 * Version: ${config.meta.version}
 */

module.exports = () => {
  return {
    postcssPlugin: 'postcss-spexop-theme',
    Once(root) {
      // Inject theme variables at the start of the root
      const themeVars = \`:root {
  /* Colors */
  --theme-primary: ${colors.primary};
  --theme-surface: ${colors.surface};
  --theme-text: ${colors.text};
  --theme-border: ${colors.border};
  
  /* Spacing */
${Object.entries(spacingValues)
  .map(([k, v]) => `  --theme-spacing-${k}: ${v}px;`)
  .join("\n")}
  
  /* Typography */
  --theme-font-family: ${typography.fontFamily};
  --theme-font-size-base: ${typography.baseSize}px;
  --theme-font-weight-regular: ${typography.weights.regular};
  --theme-font-weight-semibold: ${typography.weights.semibold};
  --theme-font-weight-bold: ${typography.weights.bold};
  
  /* Borders */
  --theme-border-width: ${borders.default}px;
  --theme-radius-subtle: ${borders.radiusSubtle}px;
  --theme-radius-relaxed: ${borders.radiusRelaxed}px;
}\`;

      root.prepend(themeVars);
    },
  };
};

module.exports.postcss = true;

// Usage in postcss.config.js:
// module.exports = {
//   plugins: [
//     require('./postcss-spexop-theme.js')(),
//   ],
// };
`;
}
