/**
 * Storybook Theme Generator
 * Generates Storybook theme configuration
 *
 * @module @spexop/theme/generators
 */

import type { SpexopThemeConfig } from "../types/SpexopThemeConfig.js";

/**
 * Generate Storybook theme
 *
 * @param config - Spexop theme configuration
 * @returns Storybook theme JavaScript string
 */
export function generateStorybook(config: SpexopThemeConfig): string {
  const { colors, typography, borders } = config;

  return `/**
 * ${config.meta.name} - Storybook Theme
 * Generated by @spexop/theme
 * Version: ${config.meta.version}
 */

import { create } from '@storybook/theming';

export const theme = create({
  base: 'light',

  // Brand
  brandTitle: ${JSON.stringify(config.meta.name)},
  brandUrl: ${JSON.stringify("https://spexop.com")},

  // Colors
  colorPrimary: ${JSON.stringify(colors.primary)},
  colorSecondary: ${JSON.stringify(colors.secondary || colors.primary)},

  // UI
  appBg: ${JSON.stringify(colors.surface)},
  appContentBg: ${JSON.stringify(colors.surfaceSecondary)},
  appBorderColor: ${JSON.stringify(colors.border)},
  appBorderRadius: ${borders.radiusRelaxed},

  // Text colors
  textColor: ${JSON.stringify(colors.text)},
  textInverseColor: ${JSON.stringify(colors.surface)},
  textMutedColor: ${JSON.stringify(colors.textMuted)},

  // Toolbar
  barTextColor: ${JSON.stringify(colors.textSecondary)},
  barSelectedColor: ${JSON.stringify(colors.primary)},
  barBg: ${JSON.stringify(colors.surface)},

  // Form colors
  inputBg: ${JSON.stringify(colors.surface)},
  inputBorder: ${JSON.stringify(colors.border)},
  inputTextColor: ${JSON.stringify(colors.text)},
  inputBorderRadius: ${borders.radiusSubtle},

  // Typography
  fontBase: ${typography.fontFamily},
  fontCode: ${typography.fontFamilyMono || "'Fira Code', monospace"},
});

export default theme;
`;
}
